spring:
  application:
    name: journal-app
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${DB_NAME}
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL}
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: weekly-sentiment-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.javaproject.journalApp.model


server:
  port: 8080
  servlet:
    context-path: /journal


weather:
  api:
    key: ${WEATHER_API_KEY}

#springdoc:
#  swagger-ui:
#    path: /docs