spring:
  application:
    name: journal-app
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${DB_NAME}
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL}
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


server:
  port: 8080
  servlet:
    context-path: /journal


weather:
  api:
    key: ${WEATHER_API_KEY}